services:
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    depends_on:
      - wordpress
      - static-site
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:user
    container_name : wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:user
    container_name : mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception
    restart: no
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:user
    container_name: redis-cache
    build: ./redis
    depends_on:
      - nginx
    networks:
      - inception
    restart: on-failure

  ftp:
    image: ftp:user
    container_name: ftp-server
    build: ./ftp-server
    volumes:
      - wordpress:/home/$FTP_USER/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - nginx
    networks:
      - inception
    restart: on-failure
    env_file:
      - .env

  static-site:
    image: static-site
    container_name: static-site
    build: ./static-site
    networks:
      - inception


volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/jrasamim/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jrasamim/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception